version: "3.9"

services:
    db:
        image: postgres:13.14-bullseye
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        restart: always

    app:
        build: ./
        container_name: backend-app
        depends_on:
            - db
        ports:
            - "3001:3001"
        volumes:
            - ./src:/usr/src/app/src
            - /usr/src/app/node_modules
        command: npm run dev
        environment:
            - APP_PORT=${APP_PORT}
            - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
            - TYPEORM_POSTGRES_HOST=${TYPEORM_POSTGRES_HOST}
            - TYPEORM_POSTGRES_PORT=${TYPEORM_POSTGRES_PORT}
            - TYPEORM_POSTGRES_USERNAME=${TYPEORM_POSTGRES_USERNAME}
            - TYPEORM_POSTGRES_PASSWORD=${TYPEORM_POSTGRES_PASSWORD}
            - TYPEORM_POSTGRES_DATABASE=${TYPEORM_POSTGRES_DATABASE}
