version: "3.9"

services:
    db:
        image: postgres:13.14-bullseye
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
    client:
        build: ./
        ports:
            - 3001:3001
        volumes:
            - ./src:/usr/src/app/src
        command: npm run dev
